# Generated by Django 4.1.2 on 2023-02-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_json", models.CharField(default="", max_length=70)),
                ("name", models.CharField(default="", max_length=70)),
                ("email", models.CharField(default="", max_length=200)),
                ("phone", models.CharField(default="", max_length=70)),
                ("address", models.CharField(default="", max_length=200)),
                ("state", models.CharField(default="", max_length=70)),
                ("city", models.CharField(default="", max_length=70)),
                ("zip_code", models.CharField(default="", max_length=70)),
            ],
        ),
    ]
