# Generated by Django 4.1.2 on 2023-02-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderUpdate",
            fields=[
                ("update_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.IntegerField(default="", max_length=100)),
                ("update_desc", models.CharField(default="", max_length=5000)),
                ("timestamp", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
