# Generated by Django 4.1.2 on 2023-02-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_contact_desc_alter_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="desc",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="orderupdate",
            name="update_desc",
            field=models.TextField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(max_length=100),
        ),
    ]
