# Generated by Django 4.1.2 on 2023-02-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_order_address_alter_orderupdate_update_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="desc",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.CharField(default="", max_length=70),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(default="", max_length=70),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(default="", max_length=70),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="item_json",
            field=models.CharField(default="", max_length=70),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(default="", max_length=70),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(default="", max_length=70),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(default="", max_length=70),
        ),
        migrations.AlterField(
            model_name="order",
            name="zip_code",
            field=models.CharField(default="", max_length=70),
        ),
        migrations.AlterField(
            model_name="orderupdate",
            name="update_desc",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategory",
            field=models.CharField(default="", max_length=50),
        ),
    ]
