# Generated by Django 4.1.2 on 2023-02-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_alter_contact_desc_alter_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
