# Generated by Django 4.1.2 on 2023-02-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_order_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(default="", max_length=200),
        ),
    ]
