# Generated by Django 4.1.2 on 2023-02-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="chead0",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="chead1",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="chead2",
            field=models.CharField(default="", max_length=500),
        ),
    ]
