# Generated by Django 4.1.2 on 2023-02-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_chead0_alter_blogpost_chead1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="chead0",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="chead1",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="chead2",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="head0",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="head1",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="head2",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(default="", max_length=50),
        ),
    ]
